In [9]:
import sys
print(sys.executable)

C:\Users\Yahya\AppData\Local\Programs\Python\Python310\python.exe

In [10]:
import sys

!{sys.executable} -m pip install pandas scikit-learn joblib Sastrawi notebook

Requirement already satisfied: pandas in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (1.6.1)
Requirement already satisfied: joblib in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (1.5.0)
Requirement already satisfied: Sastrawi in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (1.0.1)
Collecting notebook
  Downloading notebook-7.5.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.6.0)
Collecting jupyter-server<3,>=2.4.0 (from notebook)
  Downloading jupyter_server-2.18.2-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from notebook)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab<4.6,>=4.5.7 (from notebook)
  Downloading jupyterlab-4.5.7-py3-none-any.whl.metadata (16 kB)
Collecting notebook-shim<0.3,>=0.2 (from notebook)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tornado>=6.2.0 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from notebook) (6.4.2)
Collecting anyio>=3.1.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jinja2>=3.0.3 (from jupyter-server<3,>=2.4.0->notebook)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.7.2)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbconvert>=6.4.4 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: packaging>=22.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.0)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading pywinpty-3.0.3-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: pyzmq>=24 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (26.4.0)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: traitlets>=5.6.0 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.14.3)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->notebook)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting async-lru>=1.0.0 (from jupyterlab<4.6,>=4.5.7->notebook)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab<4.6,>=4.5.7->notebook)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (6.29.5)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab<4.6,>=4.5.7->notebook)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (57.4.0)
Collecting tomli>=1.2.2 (from jupyterlab<4.6,>=4.5.7->notebook)
  Downloading tomli-2.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: certifi in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook) (2025.4.26)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook) (3.10)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: requests>=2.31 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.32.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (1.2.2)
Requirement already satisfied: typing_extensions>=4.5 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (4.13.2)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: comm>=0.1.1 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (1.8.14)
Requirement already satisfied: ipython>=7.23.1 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (8.36.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (1.6.0)
Requirement already satisfied: psutil in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (7.0.0)
Requirement already satisfied: colorama in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.4.6)
Requirement already satisfied: decorator in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (5.2.1)
Requirement already satisfied: jedi>=0.16 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (2.19.1)
Requirement already satisfied: stack_data in c:\users\yahya\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\yahya\appdata\roaming\python\python310\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook) (3.0.2)
Collecting attrs>=22.2.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook)
  Downloading rpds_py-0.30.0-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook) (310)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl.metadata (2.4 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading mistune-3.2.1-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yahya\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (2.4.0)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook)
  Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: executing>=1.2.0 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\yahya\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\yahya\appdata\roaming\python\python310\site-packages (from stack_data->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.7->notebook) (0.2.3)
Downloading notebook-7.5.6-py3-none-any.whl (14.6 MB)
   ---------------------------------------- 0.0/14.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.6 MB ? eta -:--:--
    --------------------------------------- 0.3/14.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.6 MB 1.2 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/14.6 MB 1.2 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/14.6 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.3/14.6 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/14.6 MB 1.2 MB/s eta 0:00:11
   ----- ---------------------------------- 1.8/14.6 MB 1.2 MB/s eta 0:00:11
   ----- ---------------------------------- 2.1/14.6 MB 1.2 MB/s eta 0:00:11
   ------ --------------------------------- 2.4/14.6 MB 1.2 MB/s eta 0:00:11
   ------- -------------------------------- 2.6/14.6 MB 1.2 MB/s eta 0:00:10
   ------- -------------------------------- 2.9/14.6 MB 1.2 MB/s eta 0:00:10
   -------- ------------------------------- 3.1/14.6 MB 1.2 MB/s eta 0:00:10
   --------- ------------------------------ 3.4/14.6 MB 1.2 MB/s eta 0:00:10
   ---------- ----------------------------- 3.7/14.6 MB 1.2 MB/s eta 0:00:09
   ---------- ----------------------------- 3.7/14.6 MB 1.2 MB/s eta 0:00:09
   ---------- ----------------------------- 3.9/14.6 MB 1.1 MB/s eta 0:00:10
   ----------- ---------------------------- 4.2/14.6 MB 1.1 MB/s eta 0:00:10
   ----------- ---------------------------- 4.2/14.6 MB 1.1 MB/s eta 0:00:10
   ------------ --------------------------- 4.5/14.6 MB 1.1 MB/s eta 0:00:10
   ------------ --------------------------- 4.5/14.6 MB 1.1 MB/s eta 0:00:10
   ------------ --------------------------- 4.7/14.6 MB 1.1 MB/s eta 0:00:10
   ------------- -------------------------- 5.0/14.6 MB 1.1 MB/s eta 0:00:09
   -------------- ------------------------- 5.2/14.6 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 5.5/14.6 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 5.5/14.6 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 5.5/14.6 MB 1.1 MB/s eta 0:00:09
   --------------- ------------------------ 5.8/14.6 MB 1.0 MB/s eta 0:00:09
   --------------- ------------------------ 5.8/14.6 MB 1.0 MB/s eta 0:00:09
   ---------------- ----------------------- 6.0/14.6 MB 984.3 kB/s eta 0:00:09
   ---------------- ----------------------- 6.0/14.6 MB 984.3 kB/s eta 0:00:09
   ---------------- ----------------------- 6.0/14.6 MB 984.3 kB/s eta 0:00:09
   ----------------- ---------------------- 6.3/14.6 MB 927.6 kB/s eta 0:00:09
   ----------------- ---------------------- 6.3/14.6 MB 927.6 kB/s eta 0:00:09
   ----------------- ---------------------- 6.3/14.6 MB 927.6 kB/s eta 0:00:09
   ----------------- ---------------------- 6.6/14.6 MB 871.5 kB/s eta 0:00:10

  WARNING: The script wsdump.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script send2trash.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyjson5.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybabel.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jsonschema.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-trust.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-execute.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-events.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jupyter-dejavu.exe and jupyter-nbconvert.exe are installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-server.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jlpm.exe, jupyter-lab.exe, jupyter-labextension.exe and jupyter-labhub.exe are installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-notebook.exe is installed in 'C:\Users\Yahya\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: C:\Users\Yahya\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import joblib

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('../dataset/menu.csv')

df.head()

   id   nama_menu kategori                           deskripsi  harga gambar
0   1   Kue Lapis  dessert  kue lapis tradisional manis lembut  12000  1.png
1   2     Kelepon  dessert       kelepon isi gula merah kelapa  10000  2.png
2   3   Onde Onde  dessert    onde onde wijen isi kacang hijau  12000  3.png
3   4    Kue Putu  dessert      kue putu pandan isi gula merah  10000  4.png
4   5  Bika Ambon  dessert        bika ambon khas medan lembut  15000  5.png

In [3]:
df['fitur'] = (
    df['nama_menu'] + ' ' +
    df['kategori'] + ' ' +
    df['deskripsi']
)

df[['nama_menu', 'fitur']].head()

    nama_menu                                              fitur
0   Kue Lapis  Kue Lapis dessert kue lapis tradisional manis ...
1     Kelepon      Kelepon dessert kelepon isi gula merah kelapa
2   Onde Onde  Onde Onde dessert onde onde wijen isi kacang h...
3    Kue Putu    Kue Putu dessert kue putu pandan isi gula merah
4  Bika Ambon    Bika Ambon dessert bika ambon khas medan lembut

In [4]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def preprocessing(text):

    text = text.lower()

    text = stemmer.stem(text)

    return text

In [5]:
df['fitur'] = df['fitur'].apply(preprocessing)

df[['nama_menu', 'fitur']].head()

    nama_menu                                              fitur
0   Kue Lapis  kue lapis dessert kue lapis tradisional manis ...
1     Kelepon      kelepon dessert kelepon isi gula merah kelapa
2   Onde Onde  onde onde dessert onde onde wijen isi kacang h...
3    Kue Putu    kue putu dessert kue putu pandan isi gula merah
4  Bika Ambon    bika ambon dessert bika ambon khas medan lembut

In [6]:
tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(df['fitur'])

print(tfidf_matrix.shape)

(25, 73)

In [7]:
cosine_sim = cosine_similarity(tfidf_matrix)

print(cosine_sim)

[[1.         0.03621834 0.02197892 0.34609834 0.09392522 0.21663948
  0.03474716 0.         0.         0.24738964 0.         0.
  0.         0.02900016 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.03621834 1.         0.05648379 0.25882029 0.03411762 0.04307323
  0.03984264 0.04696107 0.         0.05338743 0.         0.
  0.         0.03325288 0.04335611 0.         0.04869562 0.
  0.         0.         0.         0.         0.0465932  0.
  0.        ]
 [0.02197892 0.05648379 1.         0.04717412 0.02070411 0.02613877
  0.02417831 0.02849809 0.         0.0323979  0.         0.
  0.         0.02017935 0.02631044 0.         0.02955069 0.
  0.         0.         0.         0.         0.02827485 0.
  0.        ]
 [0.34609834 0.25882029 0.04717412 1.         0.02849435 0.03597389
  0.03327577 0.03922094 0.         0.04458811 0.         0.
  0.         0.02777214 0.03621015 0.         0.0406696  0.
  0.         0.         0.         0.         0.0389137  0.
  0.        ]
 [0.09392522 0.03411762 0.02070411 0.02849435 1.         0.03538578
  0.03273177 0.         0.         0.13844991 0.         0.
  0.         0.02731811 0.         0.         0.         0.
  0.         0.07591756 0.         0.         0.         0.
  0.        ]
 [0.21663948 0.04307323 0.02613877 0.03597389 0.03538578 1.
  0.0413236  0.         0.         0.17479193 0.         0.
  0.         0.0344889  0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.03474716 0.03984264 0.02417831 0.03327577 0.03273177 0.0413236
  1.         0.         0.         0.18492191 0.         0.
  0.         0.03190215 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.10653751]
 [0.         0.04696107 0.02849809 0.03922094 0.         0.
  0.         1.         0.09280098 0.         0.         0.
  0.         0.         0.03949796 0.         0.04436232 0.
  0.         0.         0.         0.         0.13171632 0.18621565
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.09280098 1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.09014487 0.09300864 0.04781808 0.09590471 0.04931174 0.
  0.        ]
 [0.24738964 0.05338743 0.0323979  0.04458811 0.13844991 0.17479193
  0.18492191 0.         0.         1.         0.         0.
  0.         0.04274752 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.61313037
  0.73991452 0.         0.21205852 0.03408994 0.03999361 0.03864511
  0.         0.         0.07205631 0.03721198 0.         0.07750222
  0.04336677]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.61313037 1.
  0.65559437 0.         0.4799078  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.73991452 0.65559437
  1.         0.         0.22674521 0.03645093 0.24378073 0.04132158
  0.         0.         0.         0.0397892  0.         0.
  0.04637026]
 [0.02900016 0.03325288 0.02017935 0.02777214 0.02731811 0.0344889
  0.03190215 0.         0.         0.04274752 0.         0.
  0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.04335611 0.02631044 0.03621015 0.         0.
  0.         0.03949796 0.         0.         0.21205852 0.4799078
  0.22674521 0.         1.         0.5771681  0.71807845 0.03541242
  0.         0.         0.         0.03409917 0.03918855 0.
  0.03973911]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.03408994 0.
  0.03645093 0.         0.5771681  1.         0.64824901 0.03390243
  0.         0.         0.         0.03264518 0.         0.
  0.03804463]
 [0.         0.04869562 0.02955069 0.0406696  0.         0.
  0.         0.04436232 0.         0.         0.03999361 0.
  0.24378073 0.         0.71807845 0.64824901 1.         0.03977362
  0.         0.         0.         0.03829864 0.0440148  0.
  0.04463317]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.03864511 0.
  0.04132158 0.         0.03541242 0.03390243 0.03977362 1.
  0.34986932 0.36098414 0.37118204 0.40923163 0.3827764  0.39923539
  0.04312823]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.09014487 0.         0.         0.
  0.         0.         0.         0.         0.         0.34986932
  1.         0.49027632 0.42003904 0.50554237 0.51411522 0.36134199
  0.09174479]
 [0.         0.         0.         0.         0.07591756 0.
  0.         0.         0.09300864 0.         0.         0.
  0.         0.         0.         0.         0.         0.36098414
  0.49027632 1.         0.43338304 0.52160269 0.78103055 0.37282127
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.04781808 0.         0.07205631 0.
  0.         0.         0.         0.         0.         0.37118204
  0.42003904 0.43338304 1.         0.44687757 0.41354764 0.45736336
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.09590471 0.         0.03721198 0.
  0.0397892  0.         0.03409917 0.03264518 0.03829864 0.40923163
  0.50554237 0.52160269 0.44687757 1.         0.46083638 0.38443005
  0.04152885]
 [0.         0.0465932  0.02827485 0.0389137  0.         0.
  0.         0.13171632 0.04931174 0.         0.         0.
  0.         0.         0.03918855 0.         0.0440148  0.3827764
  0.51411522 0.78103055 0.41354764 0.46083638 1.         0.39532813
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.18621565 0.         0.         0.07750222 0.
  0.         0.         0.         0.         0.         0.39923539
  0.36134199 0.37282127 0.45736336 0.38443005 0.39532813 1.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.10653751 0.         0.         0.         0.04336677 0.
  0.04637026 0.         0.03973911 0.03804463 0.04463317 0.04312823
  0.09174479 0.         0.         0.04152885 0.         0.
  1.        ]]

In [8]:
indices = pd.Series(df.index, index=df['nama_menu']).drop_duplicates()

indices

nama_menu
Kue Lapis            0
Kelepon              1
Onde Onde            2
Kue Putu             3
Bika Ambon           4
Serabi               5
Donat                6
Risol                7
Lemper               8
Bronis               9
Paket Specials      10
Paket Hemat         11
Paket Sultan        12
Birthday Cake       13
Snackbox Hemat      14
Snackbox Hajat      15
Snackbox Sultan     16
Nasi Kuning         17
Nasi Ayam Geprek    18
Nasi Ayam Bakar     19
Nasi Katsu          20
Nasi Ayam Uduk      21
Nasi Bakar          22
Nasi Goreng         23
Seblak              24
dtype: int64

In [9]:
def recommend_menu(nama_menu, top_n=5):

    idx = indices[nama_menu]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:top_n+1]

    menu_indices = [i[0] for i in sim_scores]

    hasil = df[
        ['nama_menu', 'kategori', 'harga', 'gambar']
    ].iloc[menu_indices]

    return hasil

In [13]:
recommend_menu('Nasi Ayam Geprek')

          nama_menu kategori  harga  gambar
22       Nasi Bakar     nasi  22000  23.png
21   Nasi Ayam Uduk     nasi  23000  22.png
19  Nasi Ayam Bakar     nasi  25000  20.png
20       Nasi Katsu     nasi  25000  21.png
23      Nasi Goreng     nasi  20000  24.png

In [14]:
joblib.dump(tfidf, '../model/tfidf_vectorizer.pkl')

joblib.dump(cosine_sim, '../model/cosine_similarity.pkl')

joblib.dump(indices, '../model/menu_indices.pkl')

print("Model berhasil disimpan")

Model berhasil disimpan

In [15]:
import sklearn
print(sklearn.__version__)

1.6.1